const stages=[
  ['00','Foundations','Linux, C, ELF, memory, and the x86-64 ABI','00-foundations'],['01','Debugging','Crash triage, cyclic patterns, and GDB evidence','01-debugging'],['02','Stack control','Buffer overflows, ret2win, arguments, and staging','02-stack-control'],['03','Mitigations','NX, ASLR, PIE, canaries, RELRO, and planning','03-mitigations'],['04','Leaks + libc','GOT/PLT, pointer leaks, bases, and ret2libc','04-leaks-and-libc'],['05','ROP','Gadgets, pivots, syscalls, and constrained chains','05-rop'],['06','Format strings','Disclosure, positional arguments, and controlled writes','06-format-strings'],['07','Heap','Chunks, UAF, reuse, tcache, and callback control','07-heap'],['08','Advanced Linux','seccomp, SROP, linker behavior, and constraints','08-advanced-linux'],['09','Kernel intro','Safe user/kernel boundary and toy-driver reasoning','09-kernel-intro'],['10','Capstones','Design, automate, verify, and write your own chain','10-capstone']
];
const labs=[
  ['00','hello-elf','ELF inspection','runnable','hello-elf'],['00','argv-memory','ASLR + process memory','runnable','argv-memory'],['00','abi-registers','x86-64 calling convention','runnable','abi-registers'],['01','crash-course','Overflow crash triage','runnable','crash-course'],['01','find-the-offset','Cyclic offset discovery','exercise','find-the-offset'],['02','ret2win','Buffer overflow → function','runnable','ret2win'],['02','ret2arg','Overflow + register setup','runnable','ret2arg'],['02','split-input','Staged input protocol','runnable','split-input'],['04','got-leak','Pointer leak + base reasoning','runnable','got-leak'],['05','rop-call','Explicit ROP chain','runnable','rop-call'],['06','fmt-read','Format-string disclosure','runnable','fmt-read'],['06','fmt-write','Format-string %hn write','exercise','fmt-write'],['07','uaf','Stale-pointer read','runnable','uaf'],['07','chunk-inspect','Allocator observations','runnable','chunk-inspect'],['07','tcache-reuse','Same-size reuse','runnable','tcache-reuse'],['07','menu-uaf','Menu-driven UAF','runnable','menu-uaf'],['07','heap-leak-chain','UAF → callback control','runnable','heap-leak-chain'],['08','seccomp-rop','Syscall-constraint planning','fixture','seccomp-rop']
];
const stageGrid=document.querySelector('#stage-grid');
stageGrid.innerHTML=stages.map(([no,title,desc,dir])=>`<a class="stage-card" href="course/modules/${dir}/README.md"><span class="stage-no">STAGE ${no}</span><h3>${title}</h3><p>${desc}</p></a>`).join('');
const labGrid=document.querySelector('#lab-grid'); const filters=document.querySelector('#filters'); const search=document.querySelector('#lab-search'); let active='all';
['all','runnable','exercise','fixture'].forEach(filter=>{const button=document.createElement('button');button.className=`filter${filter==='all'?' active':''}`;button.textContent=filter[0].toUpperCase()+filter.slice(1);button.onclick=()=>{active=filter;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');renderLabs()};filters.appendChild(button)});
function renderLabs(){const query=search.value.toLowerCase();labGrid.innerHTML=labs.filter(([stage,name,topic,status])=>(active==='all'||status===active)&&`${stage} ${name} ${topic}`.toLowerCase().includes(query)).map(([stage,name,topic,status,dir])=>`<article class="lab-card"><span class="tag">STAGE ${stage} / ${status.toUpperCase()}</span><h3>${name}</h3><p>${topic}</p><div class="lab-links"><a href="course/labs/${stage==='00'?'00-foundations':stage==='01'?'01-debugging':stage==='02'?'02-stack':stage==='04'?'04-libc':stage==='05'?'05-rop':stage==='06'?'06-format-string':stage==='07'?'07-heap':'08-advanced-linux'}/${dir}/README.md">Read lab ↗</a><a href="course/labs/${stage==='00'?'00-foundations':stage==='01'?'01-debugging':stage==='02'?'02-stack':stage==='04'?'04-libc':stage==='05'?'05-rop':stage==='06'?'06-format-string':stage==='07'?'07-heap':'08-advanced-linux'}/${dir}/challenge.c" download>Source ↓</a></div></article>`).join('')||'<p>No labs match that search.</p>'}
search.addEventListener('input',renderLabs);renderLabs();
